# Generated by Django 3.0.8 on 2020-08-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200825_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/199'),
        ),
    ]
